### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by Chkalov-Valerii** [JavaHutt/studing#1]
Its kinda strange

https://github.com/JavaHutt/studing/blob/eefe4e8f588ddafd733db0fa835737b9e18ead4b/random.txt#L2

**Comment by Chkalov-Valerii** [comment]
aosifgvadofvhbaoidfv

**Comment by JavaHutt** [comment]
okay

**Comment by Chkalov-Valerii** [comment]
Its ok. Thanks
